# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)

# Character.create(name: "Bardock", default_image: "https://media.eventhubs.com/images/dragon-ball-fighterz/character_header_bardock_alt.jpg", command_list: "https://gamefaqs1.cbsistatic.com/faqs/71/75771-44.jpg", frame_data: "https://pbs.twimg.com/media/DZSEZoYWkAABa_m?format=jpg&name=900x900", game_id: "2")
# ColorCostume.create(title: "Colors", image_url: "/Users/kristofer/Desktop/Actualize/crosso_app/Crosso_images/Screen Shot 2020-08-26 at 7.49.15 PM.png", character_id: "1")
# Combo.create(combo_video: "cvideo.url", notation: "comands!", character_id: "1", user_id: "1")
# Dlc.create(title: "Fighterz pass 1", content: "8 Characters", game_id: "2")

# Character.create(name: "Adult Gohan", default_image: "https://media.eventhubs.com/images/dragon-ball-fighterz/character_header_adult-gohan_alt.jpg", command_list: "", frame_data: "", game_id: "2")
# Character.create(name: "Android 16", default_image: "https://media.eventhubs.com/images/dragon-ball-fighterz/character_header_android-16_alt.jpg", command_list: "", frame_data: "", game_id: "2")
# Character.create(name: "Android 17", default_image: "https://media.eventhubs.com/images/dragon-ball-fighterz/character_header_android-17_alt.jpg", command_list: "", frame_data: "", game_id: "2")
# Character.create(name: "Android 18", default_image: "https://media.eventhubs.com/images/dragon-ball-fighterz/character_header_android-18_alt.jpg", command_list: "", frame_data: "", game_id: "2")
# Character.create(name: "Android 21", default_image: "https://media.eventhubs.com/images/dragon-ball-fighterz/character_header_android-21_alt.jpg", command_list: "", frame_data: "", game_id: "2")
# Character.create(name: "Base Goku", default_image: "https://media.eventhubs.com/images/dragon-ball-fighterz/character_header_base-goku_alt.jpg", command_list: "", frame_data: "", game_id: "2")
# Character.create(name: "Base Vegeta", default_image: "https://media.eventhubs.com/images/dragon-ball-fighterz/character_header_base-vegeta_alt.jpg", command_list: "", frame_data: "", game_id: "2")
# Character.create(name: "Beerus", default_image: "https://media.eventhubs.com/images/dragon-ball-fighterz/character_header_beerus_alt.jpg", command_list: "", frame_data: "", game_id: "2")
# Character.create(name: "Blue Goku", default_image: "https://media.eventhubs.com/images/dragon-ball-fighterz/character_header_super-saiyan-blue-goku_alt.jpg", command_list: "", frame_data: "", game_id: "2")
# Character.create(name: "Blue Vegeta", default_image: "https://media.eventhubs.com/images/dragon-ball-fighterz/character_header_super-saiyan-blue-vegeta_alt.jpg", command_list: "", frame_data: "", game_id: "2")
# Character.create(name: "Broly", default_image: "https://media.eventhubs.com/images/dragon-ball-fighterz/character_header_broly_alt.jpg", command_list: "", frame_data: "", game_id: "2")
# Character.create(name: "Captain Ginyu", default_image: "https://media.eventhubs.com/images/dragon-ball-fighterz/character_header_captain-ginyu_alt.jpg", command_list: "", frame_data: "", game_id: "2")
# Character.create(name: "Cell", default_image: "https://media.eventhubs.com/images/dragon-ball-fighterz/character_header_cell_alt.jpg", command_list: "", frame_data: "", game_id: "2")
# Character.create(name: "Cooler", default_image: "https://media.eventhubs.com/images/dragon-ball-fighterz/character_header_cooler_alt.jpg", command_list: "", frame_data: "", game_id: "2")
# Character.create(name: "Frieza", default_image: "https://media.eventhubs.com/images/dragon-ball-fighterz/character_header_frieza_alt.jpg", command_list: "", frame_data: "", game_id: "2")
# Character.create(name: "Fused Zamasu", default_image: "https://media.eventhubs.com/images/dragon-ball-fighterz/character_header_fused-zamasu_alt.jpg", command_list: "", frame_data: "", game_id: "2")
# Character.create(name: "GT Goku", default_image: "https://media.eventhubs.com/images/dragon-ball-fighterz/character_header_kid-goku_alt.jpg", command_list: "", frame_data: "", game_id: "2")
# Character.create(name: "Gogeta", default_image: "https://media.eventhubs.com/images/dragon-ball-fighterz/character_header_gogeta_alt.jpg", command_list: "", frame_data: "", game_id: "2")
# Character.create(name: "Goku", default_image: "https://media.eventhubs.com/images/dragon-ball-fighterz/character_header_goku_alt.jpg", command_list: "", frame_data: "", game_id: "2")
# Character.create(name: "Goku Black", default_image: "https://media.eventhubs.com/images/dragon-ball-fighterz/character_header_goku-black_alt.jpg", command_list: "", frame_data: "", game_id: "2")
# Character.create(name: "Gotenks", default_image: "https://media.eventhubs.com/images/dragon-ball-fighterz/character_header_gotenks_alt.jpg", command_list: "", frame_data: "", game_id: "2")
# Character.create(name: "Hit", default_image: "https://media.eventhubs.com/images/dragon-ball-fighterz/character_header_hit_alt.jpg", command_list: "", frame_data: "", game_id: "2")
# Character.create(name: "Janemba", default_image: "https://media.eventhubs.com/images/dragon-ball-fighterz/character_header_janemba_alt.jpg", command_list: "", frame_data: "", game_id: "2")
# Character.create(name: "Jiren", default_image: "https://media.eventhubs.com/images/dragon-ball-fighterz/character_header_jiren_alt.jpg", command_list: "", frame_data: "", game_id: "2")
# Character.create(name: "Kefla", default_image: "https://media.eventhubs.com/images/dragon-ball-fighterz/character_header_kefla_alt.jpg", command_list: "", frame_data: "", game_id: "2")
# Character.create(name: "Kid Buu", default_image: "https://media.eventhubs.com/images/dragon-ball-fighterz/character_header_kid-buu_alt.jpg", command_list: "", frame_data: "", game_id: "2")
# Character.create(name: "Krilin", default_image: "https://media.eventhubs.com/images/dragon-ball-fighterz/character_header_krillin_alt.jpg", command_list: "", frame_data: "", game_id: "2")
# Character.create(name: "Majin Buu", default_image: "https://media.eventhubs.com/images/dragon-ball-fighterz/character_header_majin-buu_alt.jpg", command_list: "", frame_data: "", game_id: "2")
# Character.create(name: "Nappa", default_image: "https://media.eventhubs.com/images/dragon-ball-fighterz/character_header_nappa_alt.jpg", command_list: "", frame_data: "", game_id: "2")
# Character.create(name: "Piccolo", default_image: "https://media.eventhubs.com/images/dragon-ball-fighterz/character_header_piccolo_alt.jpg", command_list: "", frame_data: "", game_id: "2")
# Character.create(name: "Super Broly", default_image: "https://media.eventhubs.com/images/dragon-ball-fighterz/character_header_super-broly_alt.jpg", command_list: "", frame_data: "", game_id: "2")
# Character.create(name: "Teen Gohan", default_image: "https://media.eventhubs.com/images/dragon-ball-fighterz/character_header_gohan_alt.jpg", command_list: "", frame_data: "", game_id: "2")
# Character.create(name: "Tien", default_image: "https://media.eventhubs.com/images/dragon-ball-fighterz/character_header_tien_alt.jpg", command_list: "", frame_data: "", game_id: "2")
# Character.create(name: "Trunks", default_image: "https://media.eventhubs.com/images/dragon-ball-fighterz/character_header_trunks_alt.jpg", command_list: "", frame_data: "", game_id: "2")
# Character.create(name: "Ultra Instinct Goku", default_image: "https://media.eventhubs.com/images/dragon-ball-fighterz/character_header_ultra-instinct-goku_alt.jpg", command_list: "", frame_data: "", game_id: "2")
# Character.create(name: "Vegeta", default_image: "https://media.eventhubs.com/images/dragon-ball-fighterz/character_header_vegeta_alt.jpg", command_list: "", frame_data: "", game_id: "2")
# Character.create(name: "Vegito", default_image: "https://media.eventhubs.com/images/dragon-ball-fighterz/character_header_super-saiyan-blue-vegito_alt.jpg", command_list: "", frame_data: "", game_id: "2")
# Character.create(name: "Videl", default_image: "https://media.eventhubs.com/images/dragon-ball-fighterz/character_header_videl_alt.jpg", command_list: "", frame_data: "", game_id: "2")
# Character.create(name: "Yamcha", default_image: "https://media.eventhubs.com/images/dragon-ball-fighterz/character_header_yamcha_alt.jpg", command_list: "", frame_data: "", game_id: "2")



# Universal.create(title: "Fighting Game Community (FGC)", body: "perhaps the most common term in fighting games as it’s the only description for those who are enthusiastic about fighting games. FGC commonly refers to those who are interested and somewhat invested in fighting games (ex: playing, watching, supporting.)")
# Universal.create(title: "First to # (FT#)", body: "a set of games to be played between two players, be it tournament, money match, or standard competitive set. Common sets are 3,5, and 10 games (ex: “That was a fluke win, FT5 me.”)")
# Universal.create(title: "Footsies", body: "commonly the act of fighting within roughly a character’s length away, trying to punish whiffed moves, capitalizing on close combat mistakes (ex: “If you want to get better at King of Fighters, you have to develop some solid footsies.”)")
# Universal.create(title: "Okizeme", body: "often shortened to Oki, is an offensive set-up or mix-up usually after a knockdown, making it more difficult for the opponent to block upon their wake-up (ex: “Narukami’s sweep to 5d Oki in P4A was a nightmare to deal with.”)")
# Universal.create(title: "Losers/Winners", body: "tournament positioning with regards to a double elimination tournament. If in Losers bracket, the player can only continue playing by winning or until eliminated. If in Winners bracket, the player can continue playing after losing, dropping down to loser’s bracket (ex: “I went 1-2, I got sent to Losers in the first round.”)")
# Universal.create(title: "Match-up", body: "the reference to how two characters match up with each other competitively (ex: “Chun Li vs Zangief is a tough match-up for Zangief.”)")
# Universal.create(title: "Godlike", body: "a term used when a certain player performs an act mid-match that showcases high level skills. Can also be used to describe players who are considered to be of the best in their respective game (ex: “Daigo’s 20+ hit combo vs Momochi was godlike.”)")
# Universal.create(title: "Free", body: "derived from the arcade community sense of not having to put in more money into the arcade machine if victorious. The loser, however, had to keep paying in order to continue playing the winner, therefore making the argument that the loser, is a free game for the winner (ex: “Everyone at my local weekly tournament is so free, I never lose a match.”)")
# Universal.create(title: "Fraudulent, Fraud", body: "the perception of being better than the actual skill of play would indicate (ex: “How is he a Grand Master rank, that was free, his rank is fraudulent.”)")
# Universal.create(title: "Salt", body: "usually a feeling after losing, a combination of rage and disappointment (ex: “I can’t believe I lost to that Shadow Jago, I’m so salty.”)")
# Universal.create(title: "Cheap", body: "refers to a move, strategy, or character that is thought to be highly advantageous with little to no risk. Also, sometimes referred to as “too good” (ex: “Dragunov’s running 2 is too good, it’s such a cheap move.”)")
# Universal.create(title: "Runback", body: "another form of the word rematch, except with a bit of a salt laced in. Also, sometimes referred to as Salty Runback (ex: “Run it back, you got lucky that game.”)")
# Universal.create(title: "Bodied", body: "the most popular FGC slang term with regards to losing horribly. Bodied can also be regarded as the FGC exclusive version of “rekt”, “owned”, etc. (ex: “I got double perfected, I got bodied.”)")
# Universal.create(title: "Respect", body: "the action taken by the opponent or the player after a knockdown, showing respect often translates to not hitting a button on wake-up (ex: “He wouldn’t respect me so I woke-up uppercut.”)")
# Universal.create(title: "Bait/Baited", body: "anticipating your opponent’s action, and when they perform the presumed action, reversing the situation, leaving them vulnerable, playing to your advantage (ex: Person 1: “How did you know to backdash bait his Burst?” Person 2: “I saw he didn’t have meter to get out of the corner, so his only option was Burst.”)")
# Universal.create(title: "Dumb", body: "referring to a type of mentality, or way of play. Not calculating risk, just executing set moves or going through with a strategy without considering the consequences (ex: “Why is he just spamming hopkick when it’s launch punishable? Oh, I forgot that Claudio players like playing dumb.”)")
# Universal.create(title: "Smart", body: "the reverse of playing dumb, playing calculated, thinking about the risk/reward of certain aspects before going through with them. (ex: “Shikki rarely jumps in randomly to avoid getting anti-aired, he plays smart.”)")
# Universal.create(title: "Pop-off", body: "a celebratory act after winning a game, set, or tournament. Often seen in friendly duels, bad blood rivalries, and large high stake tournaments (ex: “Woshige’s early pop-off  vs Ogawa at EVO 2015 is one for the ages.”")
# Universal.create(title: "On Tilt", body: "the FGC version of being flustered, often occurs under pressure, or stressful situations, leading the player to make mistakes, or performing poorly at a specific moment in the match. Also, sometimes referred to as Cracking (ex: “Ibuki kept knocking me down so I woke up Ultra, I was on tilt.”)")
# Universal.create(title: "Hold that (L)", body: "a phrase that can be used when someone wins (often rather convincingly) and the runback isn’t granted (ex: “He beat me twice online and sent me a message saying ‘hold that’, now I’m salty.”)")
# Universal.create(title: "Anti-air", body: "An attack that hits in an area that is good for knocking the opponent out of the air.")
# Universal.create(title: "Airdash", body: "A dash performed in the air (44, 66 in the air). Can be done in Guilty Gear, Melty Blood, BlazBlue, and many other anime fighting games.")
# Universal.create(title: "Airthrow", body: "Throw executed in the air, leaves the opponent on the ground like a normal throw. In some games, everyone can airthrow while in others, only some characters can. In SF4, the characters that can airthrow are Cammy, Chun-li, El Fuerte, and Guile.")
# Universal.create(title: "BnB/B&B", body: "Bread and butter. Refers to basic combos that form the core of your gameplay.")
# Universal.create(title: "Buffer", body: "Pressing the inputs for an attack while in a state that prevents the move from coming out (in block/hitstun, on the ground, during another move). Moves with multiple inputs can be simplified by pressing all but the last input while unable to attack, then just a single button press will be needed for the second attack to come out.")
# Universal.create(title: "Charge", body: "Charged attacks are executed by holding a direction for a certain amount of time, then pressing another direction and an attack button. In SF4, charged moves must be held for 2 seconds. Guile’s Sonic Boom is done by holding back for 2 seconds, then pressing forward and any punch.")
# Universal.create(title: "Chip damage", body: "Special moves, when blocked, still do a small amount of damage, which can be used to chip away at an opponent’s health.")
# Universal.create(title: "Command throw", body: "A throw that is not executed using the game’s standard throw input. Cannot be teched in most games. Examples are E.Honda’s Oicho Throw and Makoto’s Karakusa.")
# Universal.create(title: "Counterpick", body: "Intentionally switching characters so that you have a better chance of beating the opponent. Can be considered a shady tactic.")
# Universal.create(title: "Crossup", body: "A deceptive attack that makes the opponent guess which direction they need to block in.")
# Universal.create(title: "Dive kick", body: "Aerial attack used by some characters to apply pressure, done by pressing down-forward+kick in the air. Used by Rufus in SF4, and Yun/Yang in SF3.")
# Universal.create(title: "Frame trap", body: "An attack that, when timed correctly, opens up enough of a gap for the opponent to try to attack but nothing the opponent does will come out fast enough to avoid being stuffed.")
# Universal.create(title: "Grappler", body: "Character with strong throws who often works hard to get in on the opponent, but does huge damage once he is in. Examples include Zangief from SF2/4, Hugo from SF3, Potemkin from GG, and Tager from BB.")
# Universal.create(title: "Infinite", body: "A combo that can be repeated an infinite number of times until the opponent is dead.")
# Universal.create(title: "Invincibility", body: "Certain attacks are invincible during their duration. Ryu’s EX Shoryuken gives him upper body invincibility and can be used to beat out almost any attack.")
# Universal.create(title: "Link", body: "Comboing from one attack to another that isn’t a cancel. Attacks can only be linked if the second attack comes out faster than the opponent recovers (see Frame Advantage).")
# Universal.create(title: "Matchup", body: "When two characters fight against each other at the pinnacle of perfect play, who has the better chance of winning. For example, Sagat vs. Zangief is a 7-3 matchup in Sagat’s favor because Zangief has a hard time getting in through Sagat’s fireball game.")
# Universal.create(title: "Meaty", body: "An attack that hits an opponent as soon as they wake up to they are forced to block it in its later active frames. This is often an attack with high active frames such as SF4 M.Bison’s crouch short. When executed correctly, gives more frame advantage due to hitting later: there are less active frames to wait through.")
# Universal.create(title: "Mixup", body: "Making the other player guess what you are about to do. Mixup options include high attacks, low attacks, throws, etc.")
# Universal.create(title: "MM", body: "Money Match. A match played between two players for money. Depending on the amount at stake, may be first to 3, first to 5, FT10, etc.")
# Universal.create(title: "Negative edge", body: "The input that occurs when a button is released.")
# Universal.create(title: "OCV", body: "One character victory. Can refer to one player winning a match for his team in team tournaments, or one character in team games such as Capcom vs. SNK 2.")
# Universal.create(title: "Option select", body: "Exploiting the game’s input detection to give yourself the best option based on a certain input. For example in SF4, if you press down+jab+short, the game may use a crouching attack, or tech a throw, or do nothing.")
# Universal.create(title: "Overhead", body: "An attack that must be blocked standing. Most jumping attacks are overheads. An example is SF4 Sagat’s toward+fierce elbow attack.")
# Universal.create(title: "Piano", body: "Method of pressing buttons where you roll your fingers across the buttons like playing a piano’s keys.")
# Universal.create(title: "Poking", body: "Using relatively safe moves to “poke” at your opponent. Ryu’s crouch forward is a strong poke that you will see many players use.")
# Universal.create(title: "Priority", body: "Determines whether an attack will beat, lose, or trade with another attack upon collision. Note: Not an actual value on a move, but rather a combination of speed, hitbox, etc.")
# Universal.create(title: "Proration", body: "Extending a combo causes the remaining hits of the combo to do less damage. In SF4, the remaining damage of a combo is reduced by 10% for every hit over 2 (multi-hit attacks such as Ryu’s EX Tatsu count as only hitting once).")



# Combo.create!(combo_video: "https://www.youtube.com/watch?v=ceKBvt52Aho&ab_channel=TrueUnderDawgGaming", notation: "Short and Simple Guide on How to Combo with Every Character in Dragon Ball FighterZ! While Each Character has Unique Abilities, the Essential Parts of the Combos remain the same!", user_id: 3, character_id: 1)
# Combo.create(combo_video: "https://www.youtube.com/watch?v=IJImjQr7CTg&ab_channel=Xuses", notation: "Plenty of amazing combos and wtf moments. I've compiled some amazing combos and comebacks for your viewing pleasure so you can level up with some new tricks.", user_id: 4, character_id: 1)
# Combo.create(combo_video: "https://www.youtube.com/watch?v=iJjQfcSsWI0&ab_channel=KuwangerKRT", notation: "L = Light, M = Medium, H = Heavy, S = Special, j = Jump, dj = Double Jump, sj = Super Jump, dl = Delay, SD = Super Dash, DR = Dragon Rush, Assist 1 = A1, Assist 2 = A2 , X(Y) =  Y hits of X(for example, jM(2) = two hits of jM), [X] = hold X (for example, [DR] = hold the DR button for the extra hits)", user_id: 5, character_id: 1)
# Combo.create(combo_video: "https://www.youtube.com/watch?v=XtYw3mt3HMw&ab_channel=MaximilianDood", notation: "", user_id: 6, character_id: 1)
# Combo.create(combo_video: "https://www.youtube.com/watch?v=XtYw3mt3HMw&ab_channel=MaximilianDood", notation: "We’re into year 3 and this is still the video I recommend to new players starting this game.", user_id: 7, character_id: 1)
# Combo.create(combo_video: "https://www.youtube.com/watch?v=dul6pMdQfpc&ab_channel=PavPlays", notation: "Are you new to FighterZ and want to know some easy pro-quality combos, or maybe a veteran that's played the game for a good amount of time but still aren't that great at the game? Don't worry my friend, with my guide, you'll be a Dragon Ball FighterZ pro in no time!", user_id: 8, character_id: 1)
# Combo.create(combo_video: "https://www.youtube.com/watch?v=UiSQygG9Zd8&ab_channel=TrueUnderDawgGaming", notation: "Base Goku's Best Combos Ranging from Easy to Advanced! Base Goku has Complex Combos that Deal Amazing Damage!", user_id: 9, character_id: 1)
# Combo.create(combo_video: "https://www.youtube.com/watch?v=x2ZMEWtBc6s&ab_channel=Xuses", notation: "Amazing one touch kill combos performed in real online matches.", user_id: 10, character_id: 1)
# Combo.create(combo_video: "https://www.youtube.com/watch?v=IS9ZBArpJP0&ab_channel=rooflemonger", notation: "Time for S3 Broly combos! His combo routes haven't changed up too much but he does have some new stuff. What he really benefits from, is all those new juicy assists out there!", user_id: 11, character_id: 1)
# Combo.create(combo_video: "https://www.youtube.com/watch?v=6Z_W9W4oTQM&ab_channel=SupersaiyanCabby28", notation: "Base Goku Best Kaioken Combos/Inputs video.", user_id: 11, character_id: 1)
# Combo.create(combo_video: "https://www.youtube.com/watch?v=jA4JJIS2nYc&ab_channel=jmcrofts", notation: "3 different touch of death combos for GT Goku. Enjoy!", user_id: 11, character_id: 1)