# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)

# Character.create(name: "Bardock", default_image: "https://media.eventhubs.com/images/dragon-ball-fighterz/character_header_bardock_alt.jpg", command_list: "https://gamefaqs1.cbsistatic.com/faqs/71/75771-44.jpg", frame_data: "https://pbs.twimg.com/media/DZSEZoYWkAABa_m?format=jpg&name=900x900", game_id: "2")
# ColorCostume.create(title: "Colors", image_url: "/Users/kristofer/Desktop/Actualize/crosso_app/Crosso_images/Screen Shot 2020-08-26 at 7.49.15 PM.png", character_id: "1")
# Combo.create(combo_video: "cvideo.url", notation: "comands!", character_id: "1", user_id: "1")
# Dlc.create(title: "Fighterz pass 1", content: "8 Characters", game_id: "2")

Character.create(name: "Adult Gohan", default_image: "https://media.eventhubs.com/images/dragon-ball-fighterz/character_header_adult-gohan_alt.jpg", command_list: "", frame_data: "", game_id: "2")
Character.create(name: "Android 16", default_image: "https://media.eventhubs.com/images/dragon-ball-fighterz/character_header_android-16_alt.jpg", command_list: "", frame_data: "", game_id: "2")
Character.create(name: "Android 17", default_image: "https://media.eventhubs.com/images/dragon-ball-fighterz/character_header_android-17_alt.jpg", command_list: "", frame_data: "", game_id: "2")
Character.create(name: "Android 18", default_image: "https://media.eventhubs.com/images/dragon-ball-fighterz/character_header_android-18_alt.jpg", command_list: "", frame_data: "", game_id: "2")
Character.create(name: "Android 21", default_image: "https://media.eventhubs.com/images/dragon-ball-fighterz/character_header_android-21_alt.jpg", command_list: "", frame_data: "", game_id: "2")
Character.create(name: "Base Goku", default_image: "https://media.eventhubs.com/images/dragon-ball-fighterz/character_header_base-goku_alt.jpg", command_list: "", frame_data: "", game_id: "2")
Character.create(name: "Base Vegeta", default_image: "https://media.eventhubs.com/images/dragon-ball-fighterz/character_header_base-vegeta_alt.jpg", command_list: "", frame_data: "", game_id: "2")
Character.create(name: "Beerus", default_image: "https://media.eventhubs.com/images/dragon-ball-fighterz/character_header_beerus_alt.jpg", command_list: "", frame_data: "", game_id: "2")
Character.create(name: "Blue Goku", default_image: "https://media.eventhubs.com/images/dragon-ball-fighterz/character_header_super-saiyan-blue-goku_alt.jpg", command_list: "", frame_data: "", game_id: "2")
Character.create(name: "Blue Vegeta", default_image: "https://media.eventhubs.com/images/dragon-ball-fighterz/character_header_super-saiyan-blue-vegeta_alt.jpg", command_list: "", frame_data: "", game_id: "2")
Character.create(name: "Broly", default_image: "https://media.eventhubs.com/images/dragon-ball-fighterz/character_header_broly_alt.jpg", command_list: "", frame_data: "", game_id: "2")
Character.create(name: "Captain Ginyu", default_image: "https://media.eventhubs.com/images/dragon-ball-fighterz/character_header_captain-ginyu_alt.jpg", command_list: "", frame_data: "", game_id: "2")
Character.create(name: "Cell", default_image: "https://media.eventhubs.com/images/dragon-ball-fighterz/character_header_cell_alt.jpg", command_list: "", frame_data: "", game_id: "2")
Character.create(name: "Cooler", default_image: "https://media.eventhubs.com/images/dragon-ball-fighterz/character_header_cooler_alt.jpg", command_list: "", frame_data: "", game_id: "2")
Character.create(name: "Frieza", default_image: "https://media.eventhubs.com/images/dragon-ball-fighterz/character_header_frieza_alt.jpg", command_list: "", frame_data: "", game_id: "2")
Character.create(name: "Fused Zamasu", default_image: "https://media.eventhubs.com/images/dragon-ball-fighterz/character_header_fused-zamasu_alt.jpg", command_list: "", frame_data: "", game_id: "2")
Character.create(name: "GT Goku", default_image: "https://media.eventhubs.com/images/dragon-ball-fighterz/character_header_kid-goku_alt.jpg", command_list: "", frame_data: "", game_id: "2")
Character.create(name: "Gogeta", default_image: "https://media.eventhubs.com/images/dragon-ball-fighterz/character_header_gogeta_alt.jpg", command_list: "", frame_data: "", game_id: "2")
Character.create(name: "Goku", default_image: "https://media.eventhubs.com/images/dragon-ball-fighterz/character_header_goku_alt.jpg", command_list: "", frame_data: "", game_id: "2")
Character.create(name: "Goku Black", default_image: "https://media.eventhubs.com/images/dragon-ball-fighterz/character_header_goku-black_alt.jpg", command_list: "", frame_data: "", game_id: "2")
Character.create(name: "Gotenks", default_image: "https://media.eventhubs.com/images/dragon-ball-fighterz/character_header_gotenks_alt.jpg", command_list: "", frame_data: "", game_id: "2")
Character.create(name: "Hit", default_image: "https://media.eventhubs.com/images/dragon-ball-fighterz/character_header_hit_alt.jpg", command_list: "", frame_data: "", game_id: "2")
Character.create(name: "Janemba", default_image: "https://media.eventhubs.com/images/dragon-ball-fighterz/character_header_janemba_alt.jpg", command_list: "", frame_data: "", game_id: "2")
Character.create(name: "Jiren", default_image: "https://media.eventhubs.com/images/dragon-ball-fighterz/character_header_jiren_alt.jpg", command_list: "", frame_data: "", game_id: "2")
Character.create(name: "Kefla", default_image: "https://media.eventhubs.com/images/dragon-ball-fighterz/character_header_kefla_alt.jpg", command_list: "", frame_data: "", game_id: "2")
Character.create(name: "Kid Buu", default_image: "https://media.eventhubs.com/images/dragon-ball-fighterz/character_header_kid-buu_alt.jpg", command_list: "", frame_data: "", game_id: "2")
Character.create(name: "Krilin", default_image: "https://media.eventhubs.com/images/dragon-ball-fighterz/character_header_krillin_alt.jpg", command_list: "", frame_data: "", game_id: "2")
Character.create(name: "Majin Buu", default_image: "https://media.eventhubs.com/images/dragon-ball-fighterz/character_header_majin-buu_alt.jpg", command_list: "", frame_data: "", game_id: "2")
Character.create(name: "Nappa", default_image: "https://media.eventhubs.com/images/dragon-ball-fighterz/character_header_nappa_alt.jpg", command_list: "", frame_data: "", game_id: "2")
Character.create(name: "Piccolo", default_image: "https://media.eventhubs.com/images/dragon-ball-fighterz/character_header_piccolo_alt.jpg", command_list: "", frame_data: "", game_id: "2")
Character.create(name: "Super Broly", default_image: "https://media.eventhubs.com/images/dragon-ball-fighterz/character_header_super-broly_alt.jpg", command_list: "", frame_data: "", game_id: "2")
Character.create(name: "Teen Gohan", default_image: "https://media.eventhubs.com/images/dragon-ball-fighterz/character_header_gohan_alt.jpg", command_list: "", frame_data: "", game_id: "2")
Character.create(name: "Tien", default_image: "https://media.eventhubs.com/images/dragon-ball-fighterz/character_header_tien_alt.jpg", command_list: "", frame_data: "", game_id: "2")
Character.create(name: "Trunks", default_image: "https://media.eventhubs.com/images/dragon-ball-fighterz/character_header_trunks_alt.jpg", command_list: "", frame_data: "", game_id: "2")
Character.create(name: "Ultra Instinct Goku", default_image: "https://media.eventhubs.com/images/dragon-ball-fighterz/character_header_ultra-instinct-goku_alt.jpg", command_list: "", frame_data: "", game_id: "2")
Character.create(name: "Vegeta", default_image: "https://media.eventhubs.com/images/dragon-ball-fighterz/character_header_vegeta_alt.jpg", command_list: "", frame_data: "", game_id: "2")
Character.create(name: "Vegito", default_image: "https://media.eventhubs.com/images/dragon-ball-fighterz/character_header_super-saiyan-blue-vegito_alt.jpg", command_list: "", frame_data: "", game_id: "2")
Character.create(name: "Videl", default_image: "https://media.eventhubs.com/images/dragon-ball-fighterz/character_header_videl_alt.jpg", command_list: "", frame_data: "", game_id: "2")
Character.create(name: "Yamcha", default_image: "https://media.eventhubs.com/images/dragon-ball-fighterz/character_header_yamcha_alt.jpg", command_list: "", frame_data: "", game_id: "2")
